markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-relative-links
  - algoliasearch-jekyll

elasticsearch:
  currentversion: 6.2.3
  previousversion: 6.2.2

searchguard:
  esmajorversion: 6
  majorversion: 6.x-20
  fullversion: 6.2.2-20.1
  nextminorversion: 6.2.2-20.2
  nextmajorversion: 6.2.2-21.0
  islatestversion: false
  allversions:
    - 6x-22
    - 6x-21
    - 6x-20
    - v5
    - v2

docroots: 
  6x-22: latest
  6x-21: 6.x-21
  6x-20: 6.x-20
  v5: v5
  v2: v2
    
index: false

labels:
  navigation:
    quickstart: Quickstart
    installation: Installation
    tls: TLS Setup
    configuration: "Configuration"
    authauth: Authentication and Authorization
    rolespermissions: "Users, Roles and Permissions"
    eeadvanced: Advanced Security Features
    dlsfls: Document- and Field-Level Security
    auditlog: Audit Logging
    compliance: Compliance
    restapi: REST API
    esstack: Integrating with the Elastic stack
    xpack: Integrating with X-Pack
    x_pack_alternatives: X-Pack Alternatives
    integration_other: Other Integrations
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    6x-22: Search Guard 6.x-22
    6x-21: Search Guard 6.x-21
    6x-20: Search Guard 6.x-20
    v5: Search Guard 5
    v2: Search Guard 2
  collections:
    docs: Documentation
    troubleshooting: Troubleshooting
    changelogs: Changelogs


relative_links:
  enabled:     true
  collections: true

baseurl: /6.x-20

collections:
  docs:
    output: true
    permalink: :title
  troubleshooting:
    output: true
    permalink: :title
  changelogs:
    output: true
    permalink: :title

algolia:
  application_id: '2ESDTH812Y'
  index_name:     '6x-20'
  record_css_selector: 'h1, h2, h3, h4, h5'
  allowed_extensions:
    - html
  settings:
    minWordSizefor1Typo: 4
    minWordSizefor2Typos: 8
    hitsPerPage: 20
    maxValuesPerFacet: 100
    version: 2
    attributesToIndex:
      - tags
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - text_all
    attributesToRetrieve: 
      - collection_name
      - text_all
      - unique_hierarchy
      - css_selector
      - url
      - tags
    ignorePlurals: true
    removeStopWords: true
    distinct: true
    attributesForFaceting:
      - category_name
      - h1
    attributesToSnippet: 
      - "text_all:150"
    attributesToHighlight:
      - text
      - text_all
    paginationLimitedTo: 1000
    attributeForDistinct: unique_hierarchy
    exactOnSingleWordQuery: attribute
    disableTypoToleranceOnAttributes:
      - h1
      - h2
      - h3
    ranking: 
      - typo
      - geo
      - words
      - filters
      - proximity
      - attribute
      - exact
      - custom
    customRanking:
      - desc(posted_at)
      - desc(weight.tag_name)
      - asc(weight.position)
    separatorsToIndex: "."
    removeWordsIfNoResults: lastWords
    queryType: prefixLast
    snippetEllipsisText: "..."
    alternativesAsExact: 
      - ignorePlurals
      - singleWordSynonym

sgversions:
  enterprise:
    - 6.2.4|22.1|13
    - 6.2.3|22.1|13
    - 6.2.2|22.1|13
    - 6.2.1|22.1|13
    - 6.1.4|22.2|13
    - 6.1.3|22.2|13
    - 6.1.2|22.2|13
    - 6.1.1|22.2|13
  compliance:
    - 6.2.4|compliance-1|13
    - 6.2.3|compliance-1|13
    - 6.2.2|compliance-1|13
    - 6.2.1|compliance-1|13